# Generated by Django 5.1.2 on 2024-10-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0004_alter_employee_email_alter_employee_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="qr_code",
            field=models.CharField(
                default="default_qr_code.png", max_length=100, unique=True
            ),
            preserve_default=False,
        ),
    ]
