# Generated by Django 5.1.2 on 2024-10-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0005_alter_employee_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
    ]
