# Generated by Django 5.1.2 on 2024-10-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0006_alter_employee_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="telephone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
