# Generated by Django 5.1.2 on 2024-10-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0007_employee_employee_id_employee_telephone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(
                editable=False, max_length=20, null=True, unique=True
            ),
        ),
    ]
