# Generated by Django 5.1.2 on 2024-10-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0008_alter_employee_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
